// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_8eKz8XTWaZgrob11yG3gTaqakuwB8VE',
    appId: '1:591740259881:web:cadd92cfdb53d0167ed638',
    messagingSenderId: '591740259881',
    projectId: 'testproj-5b726',
    authDomain: 'testproj-5b726.firebaseapp.com',
    storageBucket: 'testproj-5b726.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCECW-rS8t4W6SyLHMAM0ZD9G23UiXC5i4',
    appId: '1:591740259881:android:7dc936084dd3b0317ed638',
    messagingSenderId: '591740259881',
    projectId: 'testproj-5b726',
    storageBucket: 'testproj-5b726.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_8eKz8XTWaZgrob11yG3gTaqakuwB8VE',
    appId: '1:591740259881:web:135feec158a41ccb7ed638',
    messagingSenderId: '591740259881',
    projectId: 'testproj-5b726',
    authDomain: 'testproj-5b726.firebaseapp.com',
    storageBucket: 'testproj-5b726.firebasestorage.app',
  );
}
